import type { Neighborhood, Property } from "@/lib/types";

export const properties: Property[] = [
  {
    id: "sunlit-residences",
    title: "Sunlit Residences",
    locality: "Indiranagar",
    city: "Bengaluru",
    price: 18_500_000,
    rent: 72_000,
    beds: 3,
    baths: 3,
    area: 1680,
    type: "Apartment",
    image: "/images/sunlit-residences.jpg",
    imageAlt: "Bright modern living room with large windows",
    tags: ["Metro nearby", "Quiet lane", "Top match"],
    score: 94,
    commute: 18,
    verified: true,
    coordinates: [77.6408, 12.9784],
  },
  {
    id: "garden-terrace",
    title: "Garden Terrace",
    locality: "Koramangala",
    city: "Bengaluru",
    price: 22_000_000,
    rent: 84_000,
    beds: 3,
    baths: 3,
    area: 1920,
    type: "Apartment",
    image: "/images/garden-terrace.jpg",
    imageAlt: "Warm contemporary apartment interior",
    tags: ["Walkable", "Restaurants", "Work hub"],
    score: 91,
    commute: 14,
    verified: true,
    coordinates: [77.6245, 12.9352],
  },
  {
    id: "willow-courtyard",
    title: "Willow Courtyard",
    locality: "Whitefield",
    city: "Bengaluru",
    price: 14_200_000,
    rent: 52_000,
    beds: 3,
    baths: 2,
    area: 1540,
    type: "Apartment",
    image: "/images/willow-courtyard.jpg",
    imageAlt: "Elegant neutral living and dining space",
    tags: ["Great value", "School zone", "Clubhouse"],
    score: 88,
    commute: 24,
    verified: true,
    coordinates: [77.7499, 12.9698],
  },
  {
    id: "quiet-canopy",
    title: "Quiet Canopy Villa",
    locality: "HSR Layout",
    city: "Bengaluru",
    price: 29_500_000,
    rent: 110_000,
    beds: 4,
    baths: 4,
    area: 2480,
    type: "Villa",
    image: "/images/quiet-canopy.jpg",
    imageAlt: "Spacious modern home with wood details",
    tags: ["Green space", "Family fit", "Low noise"],
    score: 86,
    commute: 21,
    verified: true,
    coordinates: [77.6387, 12.9116],
  },
];

export const neighborhoods: Neighborhood[] = [
  {
    id: "indiranagar",
    name: "Indiranagar",
    city: "Bengaluru",
    averagePrice: 16_900,
    averageRent: 63_000,
    growth: 8.4,
    demand: "Very high",
    score: 92,
    color: "#f2a96d",
    position: { left: "53%", top: "43%" },
    summary: "Steady premium demand led by metro access, walkable dining, and a short commute to central work hubs.",
    tags: ["Metro", "Dining", "Walkable"],
  },
  {
    id: "koramangala",
    name: "Koramangala",
    city: "Bengaluru",
    averagePrice: 15_800,
    averageRent: 59_000,
    growth: 7.1,
    demand: "Very high",
    score: 90,
    color: "#e78965",
    position: { left: "38%", top: "62%" },
    summary: "A strong rental market and dense startup ecosystem keep occupancy and lifestyle demand elevated.",
    tags: ["Startups", "Cafes", "Rental demand"],
  },
  {
    id: "whitefield",
    name: "Whitefield",
    city: "Bengaluru",
    averagePrice: 11_700,
    averageRent: 46_000,
    growth: 10.6,
    demand: "High",
    score: 86,
    color: "#f0c56b",
    position: { left: "74%", top: "46%" },
    summary: "New transit connectivity and office supply are driving the city's clearest year-on-year growth story.",
    tags: ["IT corridor", "Metro", "New supply"],
  },
  {
    id: "hsr",
    name: "HSR Layout",
    city: "Bengaluru",
    averagePrice: 13_400,
    averageRent: 52_000,
    growth: 6.8,
    demand: "High",
    score: 88,
    color: "#8fbf92",
    position: { left: "48%", top: "75%" },
    summary: "Calmer residential streets and access to both ORR and Koramangala make this a balanced family choice.",
    tags: ["Family fit", "Parks", "ORR access"],
  },
  {
    id: "jp-nagar",
    name: "JP Nagar",
    city: "Bengaluru",
    averagePrice: 10_900,
    averageRent: 38_000,
    growth: 5.9,
    demand: "Moderate",
    score: 80,
    color: "#77a997",
    position: { left: "28%", top: "78%" },
    summary: "A value-focused south Bengaluru option with established amenities and a more residential pace.",
    tags: ["Value", "Schools", "Established"],
  },
];

export const trendPoints = [42, 48, 47, 55, 58, 61, 68, 71, 78, 82, 87, 94];
